algorithm_name: alaska_dead_trees_mapper
algorithm_version: main
algorithm_description: "Semantic segmentation of dead trees in Alaska using DINOv2"
repository_url: https://github.com/abarenblitt/CHM_DINOV3.git
docker_container_url: continuumio/miniconda3:latest
build_command: CHM_DINOV3/build.sh
run_command: bash CHM_DINOV3/run.sh
disk_space: 20GB
queue: maap-dps-worker-32gb
inputs:
  positional:
    - name: hf_token
      type: string
      required: true
    - name: tif_url
      type: string
      required: true
    - name: threshold
      type: string
      default: "0.30"
      required: false