algorithm_name: alaska_dead_trees_mapper
algorithm_version: main
algorithm_description: "Semantic segmentation of dead trees in Alaska using DINOv2"
repository_url: https://github.com/abarenblitt/CHM_DINOV3.git
docker_container_url: continuumio/miniconda3:latest
build_command: pip install -r requirements.txt
run_command: bash run.sh
disk_space: 20GB
queue: maap-dps-worker-32gb
inputs:
  config:
    - name: HF_TOKEN
      type: string
      required: true
    - name: TIF_URL
      type: string
      required: true
    - name: THRESHOLD
      type: string
      default: "0.30"
      required: false