name: dino_envi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - transformers
  - datasets
  - rasterio
  - evaluate
  - scikit-learn
  - numpy